#!/bin/sh
### BEGIN INIT INFO
# Provides: tika
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Tika Server
# Description: Apache Tika Server for extraction of metadata and text.
### END INIT INFO

start () {
    echo -n "Starting Tika server daemon..."

    daemon --respawn --user=tika --name=tika --verbose --command="java -jar /usr/share/java/tika-server.jar"
    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}

stop () {
    # Stop daemon
    echo -n "Stopping Tika server daemon..."

    daemon --stop --name=tika --verbose
    RETVAL=$?

    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}

restart () {
    daemon --restart --name=tika --verbose
}

status () {
    # Report on the status of the daemon
    daemon --running --verbose --name=tika
    return $?
}

case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo $"Usage: tika {start|status|stop|restart}"
        exit 3
    ;;
esac

exit $RETVAL
