#!/bin/sh

adduser --system --disabled-password tika

# load our additional service config
systemctl daemon-reload

# start while booting
systemctl enable tika

# (re)start after installation
systemctl restart tika
